### ISSUE TITLE
Add endpoint for current slot and/or epoch

### ISSUE THREAD

**Issue by moles1** [ethereum/beacon-APIs#100]
There is currently no way to query the current slot or epoch - only the previous justified, current justified, and finalized epoch.

It's possible to calculate this manually after querying the genesis time & seconds per slot, but it would be very convenient to have an endpoint for this data.

This seems like it could fit under `/eth/v1/beacon/states/{state_id}/finality_checkpoints`, but that might be a bit of a stretch. Not sure if there is another sensible endpoint it could live under, or if it should have its own.

**Comment by rolfyone** [comment]
the `/eth/v1/events` subscription event does have the slot included as part of 'head', which is what validators make use of, I think there's a PR around changing it to combine that with chain_reorg, but slot will remain in the output...

also `/eth/v1/node/syncing` has the head_slot, and sync_distance. if the sync_distance is 0, the head_slot will be 'current'

not sure if either of these help your use case?

**Comment by moles1** [comment]
Thanks, I wasn't aware of the head slot in either of those endpoints.

Interestingly, I'm testing with Lighthouse v0.3.0 and found that it still returns the numeric head slot in the `/eth/v1/node/syncing` response even if the sync distance is zero. Not sure if this is working as per the spec.

The head slot in `/eth/v1/node/syncing` suits my use case just fine, although I still feel that having access to the current epoch would be convenient as no conversion (albeit a simple one) is necessary then. But if that's not convenient to implement, feel free to close this :)

**Comment by rolfyone** [comment]
I have no problem with the concept of an endpoint that returns specifically the epoch, I'm sure it'd fit into debug or config somewhere at the very least. it's probably more sensible than making anyone jump through hoops, though it'll be a lot more expensive than a simple calculation is the other consideration. I'll leave that to the powers that be :)

**Comment by dapplion** [comment]
Closing stale issue
