### ISSUE TITLE
getStateValidatorBalances missing 404 response definition

### ISSUE THREAD

**Issue by protolambda** [ethereum/beacon-APIs#118]
See https://github.com/ethereum/eth2.0-APIs/blob/ceb555f9b40ff9c2094d038e9f70a19419e5b652/apis/beacon/states/validator_balances.yaml#L23

I think the validator_balances should be able to result in a 404 for the same reasons as the regular validators getter. Related PR: #111 missed this I think.

Also, does an out-of-range validator index result in 404 or 400? I think 404 is better, but it's not clear right now why 400 is the only thing in the spec. This applies both to the validators and validator_balances endpoints.

Edit: and should it be returning an indexed error, to specify which parts of the query were bad?

**Comment by mpetrunic** [comment]
> I think the validator_balances should be able to result in a 404 for the same reasons as the regular validators getter. Related PR: #111 missed this I think.

This could only throw 404 if state is missing and yeah we are missing that response.

> Also, does an out-of-range validator index result in 404 or 400? I think 404 is better, but it's not clear right now why 400 is the only thing in the spec. This applies both to the validators and validator_balances endpoints.

query params is just search filter here (it doesn't identify resource), so we cannot throw 404 if index/pubkey is invalid. 400 is fine for invalid index/pubkey. If pubkey is valid but not in state, we should probably ignore that.

**Comment by mcdee** [comment]
> If pubkey is valid but not in state, we should probably ignore that.

Just want to second this.  If a user has multiple deposits and wants to know the state of all of them then they should be able to query with all the relevant pubkeys in the query filter, and those that aren't present can be ignored in the response.  Having to either query each individually to avoid an error, or manage their state internally so that they can separate out known and unknown deposits would be painful.

**Comment by mpetrunic** [comment]
resolved with https://github.com/ethereum/beacon-APIs/pull/173
