### ISSUE TITLE
Links pointing to eth2.0 API

### ISSUE THREAD

**Issue by arnetheduck** [ethereum/beacon-APIs#164]
In renaming the repo, all links to https://ethereum.github.io/eth2.0-APIs/#/ were broken - it would be nice with a redirect such that old links continue to work.

**Comment by mpetrunic** [comment]
I don't think GitHub allows that 😓

**Comment by paulhauner** [comment]
If we can't redirect, another option is to raise a very simple page that has a link to the new API docs.

It took me some digging around to figure out what the new link is. I imagine it'll be quite difficult for average users when they come across these links in old docs, blogs, etc.

**Comment by mpetrunic** [comment]
@djrtwo Can we create dummy repo with old name and host some notice?

**Comment by rolfyone** [comment]
This looks stale, given that it's still broken, I'm guessing any links are now fixed and we've missed the window when this would have been helpful...
