### ISSUE TITLE
Add syncing ETA in API response

### ISSUE THREAD

**Issue by remyroy** [ethereum/beacon-APIs#166]
It would be nice to add sync time ETA in maybe `​/eth​/v1​/node​/syncing` . I know some clients have that value internally but it's just not exposed easily.

Nice use cases for this include better timing to do the deposit or warning the user not to do the deposit yet if the ETA is greater than the waiting time until the expected activation of their validator. This is to avoid the case where a validator is activated but their beacon node is still syncing.

**Comment by mpetrunic** [comment]
Would really like feedback from other teams on this matter.

cc @dapplion @ajsutton @paulhauner @arnetheduck @rauljordan @mcdee

**Comment by arnetheduck** [comment]
I doubt this will stand the test of time - clients are likely to move on to light client sync and checkpoint sync soon meaning that ETA is unlikely to be relevant for much longer - also, there's a relatively easy way to calculate it from existing data: just poll how fast head is moving.

**Comment by dapplion** [comment]
I'm opposed to implementing this since it has to make wild assumptions about the linearity of sync and future progress. The API consumer has enough information to compute an ETA if it wants to.

**Comment by ajsutton** [comment]
Teku doesn't currently provide an ETA for sync, mostly because it makes much more sense for users to just use checkpoint sync at which point the estimate is unnecessary.  Agreed that polling and calculating the estimate externally makes more sense.
