### ISSUE TITLE
validator produceBlockHeader

### ISSUE THREAD

**Issue by djrtwo** [ethereum/beacon-APIs#179]
We should add a `produceBlockHeader` endpoint on the `validator` namespace. This is to enable any proposer/build separation (PBS) constructions -- both constructions built by third parties or any PBS constructions that are added to L1 natively in the coming years.

The block header contains the critical anti-slashing data -- `slot` -- and the VC does no other validations on the data (especially into the block body) as far as I know. So it is sufficient to just send the block header to the validator and enables any construction in which the body (or some subset of the body) is no known at the time of signing. By moving to the `header` method, the VC can be agnostic to the PBS games the BN may or may not be playing (which could even change on a per-slot or per-epoch basis).

The main potential downside I see is that a VC might multiplex on multiple BNs and want to publish the signed block to multiple nodes at once. Just getting the header  would not allow for this. Due to this feature that is potentially used today, we *can* keep `produceBlock` in addition to `produceBlockHeader`, at least for now. 

Side note: any Proof-of-Execution constructions would only be on attestations rather than block proposal because the chance of sometihng like PBS making into into the protocol is very high. And because an attster attests every epoch, a validator couldn't really be lazy in this regard.

**Comment by thegostep** [comment]
This change is referred to as "blind transaction signing" in mev-boost milestone 1 consensus client changes: https://github.com/flashbots/mev-boost#implementation-plan

**Comment by mcdee** [comment]
Obtaining only a beacon block header would cause problems for systems like Vouch that obtain beacon blocks from multiple sources and select the one with the best impact on the consensus layer (parent block, most suitable attestations, size of sync committee _etc._).

As such, if a VC is not trusted with details of execution payload then that section should be returned as a root, but the remainder of the block should be fully returned.  This should still work in a PBS world, as all fields returned are public.

**Comment by paulhauner** [comment]
> As such, if a VC is not trusted with details of execution payload then that section should be returned as a root, but the remainder of the block should be fully returned. This should still work in a PBS world, as all fields returned are public.

I'm also fine with a solution where we only stub-out the `transactions` field, rather than the entire `body` field.

**Comment by djrtwo** [comment]
Although by default I wish not to create another data structure reference creating the following seems reasonable to suit this purpose:

*Please provide suggestions for the name! It's not a header really...

```python
class BeaconBlockRedactedExecution(Container):
    slot: Slot
    proposer_index: ValidatorIndex
    parent_root: Root
    state_root: Root
    body: BeaconBlockBodyRedactedExecution

## Only change is `execution_payload` to `execution_payload_root`
class BeaconBlockBodyRedactedExecution(Container):
    randao_reveal: BLSSignature
    eth1_data: Eth1Data  # Eth1 data vote
    graffiti: Bytes32  # Arbitrary data
    # Operations
    proposer_slashings: List[ProposerSlashing, MAX_PROPOSER_SLASHINGS]
    attester_slashings: List[AttesterSlashing, MAX_ATTESTER_SLASHINGS]
    attestations: List[Attestation, MAX_ATTESTATIONS]
    deposits: List[Deposit, MAX_DEPOSITS]
    voluntary_exits: List[SignedVoluntaryExit, MAX_VOLUNTARY_EXITS]
    sync_aggregate: SyncAggregate
    # Execution -- note the root here
    execution_payload_root: Root  # [New in Bellatrix]
```

> I'm also fine with a solution where we only stub-out the transactions field

This doesn't work because all of the additional values are not publicly known (e.g. `execution_payload.state_root`)

**Comment by mcdee** [comment]
> This doesn't work because all of the additional values are not publicly known (e.g. execution_payload.state_root)

Why aren't these public?  I don't see anything in these fields that would be considered confidential in terms of protecting transaction submitters, and being able to see these fields would help proposers selecting which block they want to use from a number of proposals.

(Note that if a transactions root is supplied it would also allow block proposers to verify that a bribe transaction is present in the list of transactions given the appropriate proof)

**Comment by djrtwo** [comment]
Sorry, I meant *not publicly calculable* from information from prior blocks and current assignments. 

But I also think I was not thinking about the problem correctly when I  wrote that response. A market provider could give you an `ExecutionPayloadHeader instead of full `ExecutionPayload` at which point the validator signs a `BeaconBlock`-similar object with a payload header inside the body

Nonetheless, we need to define a series of objects that has `ExecutionPayloadHeader` instead of `ExecutionPayload`:

```python
class BeaconBlockToSign(Container):
    slot: Slot
    proposer_index: ValidatorIndex
    parent_root: Root
    state_root: Root
    body: BeaconBlockBodyToSign

## Only change is `execution_payload` to `execution_payload_header`
class BeaconBlockBodyToSign(Container):
    randao_reveal: BLSSignature
    eth1_data: Eth1Data  # Eth1 data vote
    graffiti: Bytes32  # Arbitrary data
    # Operations
    proposer_slashings: List[ProposerSlashing, MAX_PROPOSER_SLASHINGS]
    attester_slashings: List[AttesterSlashing, MAX_ATTESTER_SLASHINGS]
    attestations: List[Attestation, MAX_ATTESTATIONS]
    deposits: List[Deposit, MAX_DEPOSITS]
    voluntary_exits: List[SignedVoluntaryExit, MAX_VOLUNTARY_EXITS]
    sync_aggregate: SyncAggregate
    # Execution -- note the header here
    execution_payload_header: ExecutionPayloadHeader # [New in Bellatrix]
```


There is *some* information leaked -- pretty much just in the form of `gas_used` iiuc. I don't think making this info accidentally public hurts any sort of market mechanism or someones competitive advantage.
