### ISSUE TITLE
Consider pagination of endpoints where appropriate

### ISSUE THREAD

**Issue by wemeetagain** [ethereum/beacon-APIs#22]
In Eth1 apis, certain endpoints are practically unusable because the amount of data returned is unbounded and becomes too large for certain consumers.

If we have endpoints that return larger datasets, it would be good to consider how this can be broken up into responses of manageable/bounded size. 

Suggestion brought up during EthereumJS team meeting. @ricmoo

**Comment by dapplion** [comment]
To update, on Lodestar side we implement pagination in the consumer by querying only N items per request. Most of the requests have a predictable size so it's a stable strategy

**Comment by dapplion** [comment]
Closing stale issue, there has not been demand of this feature since beacon chain launch
