### ISSUE TITLE
Standard debug API for Fork Choice

### ISSUE THREAD

**Issue by tbenr** [ethereum/beacon-APIs#231]
To allow monitoring and debugging tools for inspect and visualize fork choice state (like protoarray) across multiple clients, it might be useful to have standard debug API exposing a minimal set of information that is useful and easily exposable by all implementations.
Some clients have already implemented their own specific API. Having a standard could encourage and facilitate additional tools development (like https://github.com/tbenr/protovis)

**Comment by tbenr** [comment]
Currently, Teku is exposing this
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/15999009/186643717-cd7ed5e3-557a-4a02-aa02-f59f6397f3aa.png">

**Comment by protolambda** [comment]
In favor of this. The protovis tool is awesome. It doesn't have to enshrine the protoarray however imho. Just a "forkchoice" endpoint that dumps all these weights and relations is fine, there are no indices in here, that's an implementation detail.

Nit: it would be nice to format those checkpoint objects as json objects instead of stringified data.

**Comment by protolambda** [comment]
Current forkchoice implementations often don't represent gap-slots as nodes, even though the protoarray and other methods can be adapted for that. Should this endpoint output nodes for gap slots? Technically forkchoice should handle these.

**Comment by terencechain** [comment]
+1 This will be great

Prysm plans to expose this: https://github.com/prysmaticlabs/prysm/blob/4c600cb1963840475033f8985f7d7f1b8ed5fec4/proto/prysm/v1alpha1/debug.proto#L101

**Comment by mpetrunic** [comment]
Could someone open PR specifying that endpoint? 😊

**Comment by rolfyone** [comment]
> 

I'll put a PR up and we can go from there...
