### ISSUE TITLE
constrain `/eth/v1/beacon/states/{state_id}/validators`

### ISSUE THREAD

**Issue by rolfyone** [ethereum/beacon-APIs#252]
As an unbound api, the validators list is quite large and has caused issues a number of times.

I can see a couple of obvious answers:
 - deprecate this api and find out more context about how it's currently used so that we can provide better apis
 - change the validator `id` param to be required, so that requests not providing it can be rejected, or at least require that one of the query parameters is passed. Status=active_ongoing would still likely be an ongoing problem for responses.
 - truncate the request to a number of validators in the response - this still takes the hit of generating the data initially, so it's probably the most hacky possible solution.

My main concern is that this is an api that can often timeout due to factors such as internet connection speed and timeouts, and subsequent calls could effectively DOS the beacon-api being queried...

To me this endpoint would be far more at home in the DEBUG namespace, the way it is currently implemented. It does get used heavily as it's got a lot of information, but it's overly expensive for the api to provide.

I'd love to have more information about why this api is heavily used, and see if we have alternatives that might be more targeted.

**Comment by mcdee** [comment]
I am unaware of what issues this endpoint has caused, do you have any links to them?

Regarding usage: 

- `ethdo` uses it for various reasons, most recently to obtain a snapshot of validator state to allow offline generation of withdrawal credentials change operations
- `chaind` uses it to obtain state of all validators for each epoch (primarily for balance and any changes to the various _epoch values)

Being able to obtain all validators is very useful.

> My main concern is that this is an api that can often timeout due to factors such as internet connection speed and timeouts, and subsequent calls could effectively DOS the beacon-api being queried...

The API was never designed to be publicly accessible, so I would not consider a DOS attack as relevant.

> [...] it's overly expensive for the api to provide.

Would be interesting to know why this is.  Perhaps if there is a way of reducing the impact then that would help.

**Comment by michaelsproul** [comment]
Lighthouse has no issue with returning the full validator set as it has to do the same amount of work behind the scenes to reconstruct the full state anyway (we can't reconstruct partial states like Teku can). Our new smaller archive node doesn't change this property, and I suspect many of the other clients are in the same boat as us.

I vote for leaving the API as-is

**Comment by rolfyone** [comment]
I don't have specific links but 
 - users reporting validators endpoint timing out
 - infura getting DOS'd by that endpoint effectively (which is admittedly no longer an issue, as it's deprecated)
these were the two main things I recall, it's a lot of data, so it tends to wreak havoc on home connections at the very least...

If we're happy with it, that's fine - I can close this ticket and we've at least discussed...

**Comment by arnetheduck** [comment]
Nimbus, like lighthouse, has no particular performance problem with this request (in relation to other state-based requests).

**Comment by rolfyone** [comment]
Ok cool - at least now we've had the discussion. will close this issue.
