### ISSUE TITLE
Add new endpoint to support downloading of blobs (EIP-4844)

### ISSUE THREAD

**Issue by jimmygchen** [ethereum/beacon-APIs#282]
Raised by @ralexstokes in this PR #271

The above PR adds new types to support EIP-4844l, however there is currently no endpoint for users to download blobs from their local CL nodes.

@0xGabi suggested the following:

> I think we should only allow to download a list of `blobs_sidecar` using the `block_id` identifier. For example: `/eth/v1/beacon/blobs_sidecar/{block_id}`. Downloading a single blob could be handle with a higher level library and reduce CL complexity.

**Comment by 0xGabi** [comment]
It was a mistake on my side. I copied one example from the beacon-api website and didn't realize it was a `v2` example. We have to start with `v1` 👍

**Comment by jimmygchen** [comment]
Thanks, updated the description :)

**Comment by jimmygchen** [comment]
I have implemented this endpoint in Lighthouse, [PR here](https://github.com/sigp/lighthouse/pull/3830). Will pick up the Beacon API spec early next week.

**Comment by jimmygchen** [comment]
Completed in #286
