### ISSUE TITLE
Remove BLS_TO_EXECUTION_CHANGE from event stream

### ISSUE THREAD

**Issue by potuz** [ethereum/beacon-APIs#283]
In  #248 the BLS_TO_EXECUTION_CHANGE  messages were added to the event stream. Given that 

1. the vast majority of validators have BLS withdrawal credentials
2. There's a strong incentive to submit these messages as soon as possible
3. There is no current need in clients for such a stream

I want to explore removal of this feature, at least until the expected volume of these changes diminishes.

**Comment by mcdee** [comment]
I don't think that there is going to be a particularly high volume of these messages, given that we know they are bounded at under 290,000 and it's unlikely that everyone will be rushing to send these immediately.

The endpoint may be useful for analysis of when these messages are sent and received across the network, as well as picking up on conflicting messages where more than one entity has access to the validator private key.

I'm not going to fight to keep it, but I don't think that volume of messages should be a major concern given that attestation events significantly exceed this number every few minutes.

**Comment by rkapka** [comment]
Now that Capella has happened, I think we can close the issue.
