### ISSUE TITLE
Known API Consumers

### ISSUE THREAD

**Issue by djrtwo** [ethereum/beacon-APIs#29]
While we are actively iterating on and thinking about the API, it would be worthwhile to maintain a list of early API consumers. Please post them in the comments below and I'll update the list her

* https://github.com/wealdtech/ethdo  -- talks to prysm nodes today to obtain bits and pieces of information, and has features such as sending voluntary exits
* https://github.com/gobitfly/eth2-beaconchain-explorer -- block explorer consumes prysm APIs and (I think) lighthouse
* https://github.com/rocket-pool/smartnode -- node software for a decentralized staking pool. currently consumes lighthouse APIs, with prysm integration in progress. currently queries eth2 config, the beacon head state, and validator status.
* https://beacon.etherscan.io (closed source) Talks to Prysm via json rest api

**Comment by moles1** [comment]
https://github.com/rocket-pool/smartnode -- node software for a decentralized staking pool. currently consumes lighthouse APIs, with prysm integration in progress. currently queries eth2 config, the beacon head state, and validator status.

**Comment by prestonvanloon** [comment]
https://beacon.etherscan.io (closed source) Talks to Prysm via json rest api

**Comment by rolfyone** [comment]
Should this list live on in markdown?

**Comment by dapplion** [comment]
With the spec being quite stable now I'm not sure of the value of this list. I don't see the value of adding this list given its maintenance cost. Anyone against closing this issue?
