### ISSUE TITLE
Next versioned release

### ISSUE THREAD

**Issue by wemeetagain** [ethereum/beacon-APIs#310]
Curious when the next release here will be?
Have any of the maintainers here discussed what the release cadence will be moving forward?

**Comment by rolfyone** [comment]
I tried to get one going, but we were waiting on the next version of consensus-specs, and its kind of blocking so I may just have to make one. I'd like one before merging all the deneb content...

**Comment by rolfyone** [comment]
I had bigger fish to fry, but yes, thanks for commenting. Alternatively we can ship and reference the spec RC...

**Comment by ralexstokes** [comment]
slightly off-topic but what is the reason releases in this repo are blocked on releases from the cl-specs repo?

**Comment by ralexstokes** [comment]
for future hard forks, we may want to follow the same pattern w/ having pre-releases like the CL specs, if we in fact want to couple them together

**Comment by rolfyone** [comment]
released! Closing ticket.
