### ISSUE TITLE
DNS failure 

### ISSUE THREAD

**Issue by kavehtehrani** [ethereum/beacon-APIs#320]
http://public-mainnet-node.ethereum.org/

fails to resolve as of 2023-05-24.

**Comment by kavehtehrani** [comment]
https://dnschecker.org/all-dns-records-of-domain.php?query=public-mainnet-node.ethereum.org%2F&rtype=ALL&dns=cloudflare

**Comment by michaelsproul** [comment]
I think it's just a placeholder, I'm not sure it ever worked

better to run your own BN locally, or use a public one from some provider e.g. QuickNode: https://www.quicknode.com/docs

**Comment by rolfyone** [comment]
It was a placeholder that wasn't supposed to resolve, it's since been changed to localhost, so we can close this issue.
