### ISSUE TITLE
#409 appears to have broken display

### ISSUE THREAD

**Issue by mcdee** [ethereum/beacon-APIs#413]
https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev shows the following:

![screenshot_2024-01-15-140724](https://github.com/ethereum/beacon-APIs/assets/511384/5336d8ae-0c13-4a4d-a03b-7bee2aee92c5)

Guess this is related to #409 where the openapi version was updated.

**Comment by jeluard** [comment]
Ouch! Probably can be solved by moving to a more recent version of [swagger-ui](https://github.com/swagger-api/swagger-ui). My bad for letting the slip through.

If not, #409 can always be reverted.
