### ISSUE TITLE
Eth1 backwards compatibility

### ISSUE THREAD

**Issue by GregTheGreek** [ethereum/beacon-APIs#6]
@GregTheGreek commented on [Wed Oct 16 2019](https://github.com/ethereum/eth2.0-specs/issues/1433)

## Introduction

This issue details the JSON RPC API that is need on the Eth2 EE  in order to support an Eth1 execution environment. This will not be relevant until Phase2, but discussions should begin now.

### Rational

Migrating contract state to Eth2.0 is an essential step in the roadmap (not covered in this document), this requires backwards compatibility for existing developer tooling such as [ethers.js](www.github.com/ethers-io/ethers.js) and [web3.js](www.github.com/ethereum/web3.js). Otherwise all DApps currently utilizing Eth1 contracts would not be useable (i.e the web-apps would quite literally blow up).

## API Specification

The specification for Eth1 can be found [here](www.github.com/ethereum/wiki/wiki/JSON-RPC), and should be implemented 1-1. Naturally, this should be fairly trivial since most languages already have an existing Eth1 implementation, with a fully function JSON RPC.

It should be noted that there is support for pub/sub (web sockets), although most providers and DApps should be checking for fallbacks, we should be implementing both the JSON-RPC schema and pub/sub.

**Comment by villanuevawill** [comment]
As a quick precursor, the API would actually live within relay or state-provider nodes (vs. to validators). It would be interesting to build a standard for these nodes that allow for communication with multiple different EEs in a similar format.

**Comment by GregTheGreek** [comment]
Relayers make a lot of sense. I'm wondering if we're going to need some sort of a gateway to manage the api's, allows the users to interact with one beacon node, and the beacon node routes the request to the appropriate sub component (relayer, validator, etc...)

**Comment by mpetrunic** [comment]
Don't think this is relevant as eth1 json rpc api is preserved via execution engine
